# Generated by Django 3.1 on 2020-08-11 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enc_dec', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='method',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
